-- V15 (Step 32): attachments — evidence files attached to a PAYMENT (receipt) or
-- a MEMBER profile (contract / CCCD scan / paperwork). Per docs/monkey_ai/01-DOMAIN.md
-- §15 and 02-ARCHITECTURE.md §4:
--   * bytes live in PostgreSQL (BYTEA), never on a filesystem — no path vector;
--   * every row carries owner_id for tenant isolation (cross-owner -> 404 in app);
--   * a file belongs to exactly one target; money/math never depend on it.
-- Legal size + content types are SECURITY settings in system_settings
-- (storage_attachment_max_mb / storage_attachment_allowed_types), so limits can
-- change without a migration.

CREATE TABLE attachments (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id             BIGINT NOT NULL REFERENCES owner_accounts(id),
  entity_type          TEXT NOT NULL CHECK (entity_type IN ('PAYMENT', 'MEMBER')),
  entity_id            BIGINT NOT NULL,
  original_name        TEXT NOT NULL,
  content_type         TEXT NOT NULL,
  size_bytes           BIGINT NOT NULL CHECK (size_bytes > 0),
  content              BYTEA NOT NULL,
  uploaded_by_user_id  BIGINT REFERENCES users(id),
  uploaded_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_attachments_owner_entity
  ON attachments(owner_id, entity_type, entity_id);