-- V16 (Step 33): owner-local phone blacklist. Per docs/monkey_ai/06-SETTINGS-TEMPLATES-RISK.md
-- §4.1 the blacklist is scoped to one owner (tenant) — never global/public. A phone the
-- owner will not onboard is rejected on add-member / add-share (409 with the reason).
-- Unlisting is soft (active = false); rows are never deleted so the history stays auditable.

CREATE TABLE member_blacklists (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id            BIGINT NOT NULL REFERENCES owner_accounts(id),
  phone               TEXT NOT NULL,
  reason              TEXT,
  active              BOOLEAN NOT NULL DEFAULT true,
  created_by_user_id  BIGINT REFERENCES users(id),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_member_blacklists_owner_phone ON member_blacklists(owner_id, phone);
CREATE INDEX idx_member_blacklists_owner_active ON member_blacklists(owner_id, active);
