-- V1 (Step 02): identity tables only. Currencies seed arrives in V3 (Step 05) per docs/monkey_ai/07-MULTI-CURRENCY.md §7.

CREATE TABLE users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         TEXT UNIQUE,
  phone         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  full_name     TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE | SUSPENDED | CLOSED
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE user_roles (
  user_id BIGINT NOT NULL REFERENCES users(id),
  role    TEXT NOT NULL,                          -- HOST | MEMBER | ADMIN
  PRIMARY KEY (user_id, role)
);

CREATE INDEX idx_user_roles_role ON user_roles(role);
