-- V2.1 (Step 04): host-scoped member profiles. V3 stays reserved for Step 05 currencies + groups.

CREATE TABLE member_profiles (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id   BIGINT NOT NULL REFERENCES owner_accounts(id),
  full_name  TEXT NOT NULL,
  phone      TEXT NOT NULL,
  note       TEXT,
  status     TEXT NOT NULL DEFAULT 'ACTIVE',   -- ACTIVE | INACTIVE | BLOCKED
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX uq_member_profiles_owner_phone ON member_profiles(owner_id, phone);
CREATE INDEX idx_member_profiles_owner ON member_profiles(owner_id);
