-- V2 (Step 03): owner tenant accounts. default_currency arrives in V3 with currencies (07-MULTI-CURRENCY §4.2).

CREATE TABLE owner_accounts (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        BIGINT NOT NULL UNIQUE REFERENCES users(id),
  display_name   TEXT NOT NULL,
  status         TEXT NOT NULL DEFAULT 'ACTIVE',   -- ACTIVE | SUSPENDED | CLOSED
  cccd           TEXT,
  bank_name      TEXT,
  bank_account   TEXT,
  account_holder TEXT,
  zalo           TEXT,
  city           TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE audit_events (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT REFERENCES users(id),
  entity_type   TEXT NOT NULL,
  entity_id     TEXT NOT NULL,
  action        TEXT NOT NULL,
  payload_json  TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_entity ON audit_events(entity_type, entity_id);
