-- V3 (Step 05): currencies seed + owner default + groups with currency FK and minor-unit money.
-- Per docs/monkey_ai/07-MULTI-CURRENCY.md §4 and §7.

CREATE TABLE currencies (
  code        CHAR(3) PRIMARY KEY,          -- ISO 4217
  name        TEXT NOT NULL,
  symbol      TEXT NOT NULL,
  exponent    SMALLINT NOT NULL CHECK (exponent BETWEEN 0 AND 4),
  rounding    TEXT NOT NULL DEFAULT 'HALF_UP',
  active      BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO currencies (code, name, symbol, exponent) VALUES
  ('VND', 'Vietnamese dong', 'd', 0),
  ('KHR', 'Cambodian riel', 'CR', 0),
  ('LAK', 'Lao kip', 'K', 0),
  ('THB', 'Thai baht', 'THB', 2),
  ('USD', 'US dollar', '$', 2),
  ('SGD', 'Singapore dollar', 'S$', 2);

ALTER TABLE owner_accounts
  ADD COLUMN default_currency CHAR(3) NOT NULL DEFAULT 'VND' REFERENCES currencies(code);

CREATE TABLE groups (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id          BIGINT NOT NULL REFERENCES owner_accounts(id),
  code              TEXT NOT NULL,
  name              TEXT NOT NULL,
  type              TEXT NOT NULL CHECK (type IN ('BIDDING', 'FIXED')),
  base_amount       BIGINT NOT NULL CHECK (base_amount > 0),
  share_count       INTEGER NOT NULL CHECK (share_count >= 2),
  cycle_unit        TEXT NOT NULL CHECK (cycle_unit IN ('DAY', 'WEEK', 'MONTH')),
  cycle_count       INTEGER NOT NULL CHECK (cycle_count >= 1),
  start_at          DATE,
  status            TEXT NOT NULL DEFAULT 'DRAFT'
                      CHECK (status IN ('DRAFT', 'RECRUITING', 'READY', 'RUNNING', 'COMPLETED', 'CANCELLED')),
  host_fee_type     TEXT NOT NULL DEFAULT 'NONE'
                      CHECK (host_fee_type IN ('NONE', 'FIXED_PER_CYCLE', 'PERCENT_OF_POT', 'FIRST_CYCLE_TO_HOST')),
  host_fee_minor    BIGINT NOT NULL DEFAULT 0 CHECK (host_fee_minor >= 0),
  host_fee_bps      INTEGER NOT NULL DEFAULT 0 CHECK (host_fee_bps >= 0),
  min_bid           BIGINT NOT NULL DEFAULT 0 CHECK (min_bid >= 0),
  max_bid           BIGINT NOT NULL DEFAULT 0,
  bid_step          BIGINT NOT NULL DEFAULT 1000 CHECK (bid_step > 0),
  tie_break         TEXT NOT NULL DEFAULT 'EARLIEST_BID'
                      CHECK (tie_break IN ('LOWEST_MEMBER_CODE', 'EARLIEST_BID', 'HOST_DECISION')),
  late_fee_type     TEXT NOT NULL DEFAULT 'NONE' CHECK (late_fee_type IN ('NONE', 'FIXED', 'PERCENT_PER_DAY')),
  late_fee_value    BIGINT NOT NULL DEFAULT 0 CHECK (late_fee_value >= 0),
  bid_open_offset   INTEGER NOT NULL DEFAULT 0,
  bid_close_offset  INTEGER NOT NULL DEFAULT 0,
  allow_multi_share BOOLEAN NOT NULL DEFAULT TRUE,
  currency          CHAR(3) NOT NULL REFERENCES currencies(code),
  rules_frozen      BOOLEAN NOT NULL DEFAULT FALSE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT groups_max_bid_lt_base CHECK (max_bid < base_amount),
  CONSTRAINT groups_fee_nonneg CHECK (host_fee_minor >= 0 AND host_fee_bps >= 0)
);

CREATE UNIQUE INDEX uq_groups_owner_code ON groups(owner_id, code);
CREATE INDEX idx_groups_owner_status ON groups(owner_id, status);
