-- V4 (Step 06): group shares. One row per share; a member may hold many (multi-share).
-- Per docs/monkey_ai/02-ARCHITECTURE.md §4 and 01-DOMAIN.md §6 (share states).
-- won_cycle_id gains its FK to cycles in V5 (Step 08) once cycles exist.

CREATE TABLE group_shares (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id          BIGINT NOT NULL REFERENCES groups(id),
  member_profile_id BIGINT NOT NULL REFERENCES member_profiles(id),
  share_no          INTEGER NOT NULL CHECK (share_no >= 1),
  status            TEXT NOT NULL DEFAULT 'ALIVE'
                      CHECK (status IN ('ALIVE', 'DEAD', 'DEFAULTED', 'EXITED')),
  won_cycle_id      BIGINT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_group_shares_group_no ON group_shares(group_id, share_no);
CREATE INDEX idx_group_shares_member ON group_shares(member_profile_id);
