-- V5 (Step 08): cycles + group_shares.won_cycle_id FK.
-- Per docs/monkey_ai/02-ARCHITECTURE.md §4 and 01-DOMAIN.md §7 (cycle lifecycle):
--   DRAFT -> OPEN -> BIDDING -> CLOSED_FOR_CALC -> PAYOUT_PENDING -> SETTLED -> ARCHIVED
-- FIXED groups and the last BIDDING cycle skip BIDDING.

CREATE TABLE cycles (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id        BIGINT NOT NULL REFERENCES groups(id),
  cycle_no        INTEGER NOT NULL CHECK (cycle_no >= 1),
  status          TEXT NOT NULL
                    CHECK (status IN ('DRAFT', 'OPEN', 'BIDDING', 'CLOSED_FOR_CALC',
                                      'PAYOUT_PENDING', 'SETTLED', 'ARCHIVED', 'FAILED')),
  currency        CHAR(3) NOT NULL REFERENCES currencies(code),
  open_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  bid_close_at    TIMESTAMPTZ,
  due_at          TIMESTAMPTZ,
  winner_share_id BIGINT,
  winning_bid     BIGINT,
  gross_pot       BIGINT,
  host_fee        BIGINT,
  net_payout      BIGINT,
  calculated_at   TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_cycles_group_no UNIQUE (group_id, cycle_no),
  CONSTRAINT cy_winner_pay_nonneg CHECK (host_fee IS NULL OR host_fee >= 0),
  CONSTRAINT cy_bid_nonneg CHECK (winning_bid IS NULL OR winning_bid >= 0)
);

ALTER TABLE group_shares
  ADD CONSTRAINT fk_group_shares_won_cycle
  FOREIGN KEY (won_cycle_id) REFERENCES cycles(id);

CREATE INDEX idx_cycles_group_status ON cycles(group_id, status);