-- V6 (Step 09): sealed bidding.
-- Per docs/monkey_ai/02-ARCHITECTURE.md §4 and 01-DOMAIN.md §8 (bidding rules):
--   one bid per share per cycle; member can update own bid until close;
--   LATEST bid wins; after close, bids are immutable.
-- Scaled back per Step 09 decision: host enters bids on behalf of members;
-- per-share member write auth arrives with the member portal (Step 13).
-- Sealed: GET /cycles/{id}/summary hides amounts before bid_close_at.

CREATE TABLE bids (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id       BIGINT NOT NULL REFERENCES cycles(id),
  share_id       BIGINT NOT NULL REFERENCES group_shares(id),
  amount_minor   BIGINT NOT NULL CHECK (amount_minor >= 0),
  currency       CHAR(3) NOT NULL REFERENCES currencies(code),
  submitted_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  is_latest      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Latest wins: one live bid per share per cycle, history preserved.
CREATE UNIQUE INDEX uq_bids_cycle_share_latest
  ON bids(cycle_id, share_id) WHERE is_latest;

CREATE INDEX idx_bids_cycle_latest ON bids(cycle_id, is_latest);
CREATE INDEX idx_bids_share ON bids(share_id);