-- V7 (Step 10): append-only ledger entries.
-- Per docs/monkey_ai/02-ARCHITECTURE.md §4 and 01-DOMAIN.md §10 (ledger rules):
--   every cycle settle writes one CONTRIBUTION obligation per paying share,
--   one HOST_FEE income entry, one PAYOUT obligation to the winner.
--   Never delete rows; reverse with a reversing entry (later steps).
-- direction is IN/OUT relative to the group pot: contributions IN, host fee + payout OUT.
-- member_profile_id is nullable: HOST_FEE entries belong to no member.

CREATE TABLE ledger_entries (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id          BIGINT NOT NULL REFERENCES groups(id),
  cycle_id          BIGINT NOT NULL REFERENCES cycles(id),
  share_id          BIGINT REFERENCES group_shares(id),
  member_profile_id BIGINT REFERENCES member_profiles(id),
  type              TEXT NOT NULL
                      CHECK (type IN ('CONTRIBUTION', 'HOST_FEE', 'PAYOUT',
                                      'LATE_FEE', 'OTHER_FEE')),
  direction         TEXT NOT NULL CHECK (direction IN ('IN', 'OUT')),
  amount_minor      BIGINT NOT NULL CHECK (amount_minor > 0),
  currency          CHAR(3) NOT NULL REFERENCES currencies(code),
  status            TEXT NOT NULL DEFAULT 'UNPAID'
                      CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID', 'WAIVED')),
  due_at            TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Duplicate-close insurance: at most one contribution/payout per share per cycle
-- and one host fee per cycle. LATE_FEE is intentionally not covered (one per
-- overdue day is allowed, added in Step 11).
CREATE UNIQUE INDEX uq_ledger_cycle_share_type
  ON ledger_entries(cycle_id, share_id, type)
  WHERE type IN ('CONTRIBUTION', 'PAYOUT');

CREATE UNIQUE INDEX uq_ledger_cycle_host_fee
  ON ledger_entries(cycle_id) WHERE type = 'HOST_FEE';

CREATE INDEX idx_ledger_group_cycle ON ledger_entries(group_id, cycle_id);
CREATE INDEX idx_ledger_share ON ledger_entries(share_id);
