-- V8 (Step 11): payments + payment_allocations.
-- Per docs/monkey_ai/02-ARCHITECTURE.md §4 and 01-DOMAIN.md §10 (ledger rules):
--   host records a real-world payment and allocates it to ledger obligations;
--   a payment may settle one or many obligations; never delete rows.
-- Per docs/monkey_ai/07-MULTI-CURRENCY.md §4.5: money is BIGINT minor units,
--   payment.currency must equal group.currency (app enforces, 409 on mismatch).
-- LATE_FEE rows are deferred beyond Step 11 (user decision 2026-10-06).

CREATE TABLE payments (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id           BIGINT NOT NULL REFERENCES groups(id),
  received_by_host_id BIGINT NOT NULL REFERENCES owner_accounts(id),
  amount_minor       BIGINT NOT NULL CHECK (amount_minor > 0),
  currency           CHAR(3) NOT NULL REFERENCES currencies(code),
  method             TEXT NOT NULL DEFAULT 'CASH'
                       CHECK (method IN ('CASH', 'BANK_TRANSFER', 'OTHER')),
  paid_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  note               TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE payment_allocations (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id      BIGINT NOT NULL REFERENCES payments(id),
  ledger_entry_id BIGINT NOT NULL REFERENCES ledger_entries(id),
  amount_minor    BIGINT NOT NULL CHECK (amount_minor > 0),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_payments_group ON payments(group_id);
CREATE INDEX idx_alloc_payment ON payment_allocations(payment_id);
CREATE INDEX idx_alloc_entry ON payment_allocations(ledger_entry_id);

-- One payment allocates to a given obligation at most once (service merges/splits
-- across payments instead); cumulative over-pay protection is enforced in service.
CREATE UNIQUE INDEX uq_alloc_payment_entry
  ON payment_allocations(payment_id, ledger_entry_id);
